name: Teraform-Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        name: Checkout source code

      - name: Run Terraform-Docs
        run: make test_documentation
